import AppShellDemo from "@/components/app-shell";
import IrTableComponent from "@/components/ir-able";
import { Center, Container, Grid, Text } from "@mantine/core";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Ir() {
  const [irData, setIrData] = useState<any>();
  const [pageLoading, setPageLoading] = useState<boolean>(true);

  async function getIrData() {
    const rawData = await fetch("/api/fetch-ir-data");
    const irData = await rawData.json();
    return irData.data;
  }

  useEffect(() => {
    getIrData().then((res: any) => {
      setIrData(res);
    });
    setPageLoading(false);
  }, []);

  if (pageLoading) {
    return <></>;
  } else {
    return (
      <>
        <Head>
          <title>IR Sensor</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppShellDemo>
          <Container>
            <Grid columns={12} mt={30}>
              <Grid.Col md={4}></Grid.Col>
              <Grid.Col md={4}>
                <Center mx={"auto"}>
                  <Text>IR SENSOR</Text>
                </Center>
                <Center mx={"auto"}>
                  {irData && irData.length ? (
                    <>
                      <IrTableComponent data={irData} />
                    </>
                  ) : (
                    <></>
                  )}
                </Center>
              </Grid.Col>
              <Grid.Col md={4}></Grid.Col>
            </Grid>
          </Container>
        </AppShellDemo>
      </>
    );
  }
}
