import AppShellDemo from "@/components/app-shell";
import UlraSonicTableComponent from "@/components/ultrasonic-table";
import { Center, Container, Grid, Text } from "@mantine/core";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Ultrasonic() {
  const [ulrasonicData, setUltrasonicIrData] = useState<any>();
  const [pageLoading, setPageLoading] = useState<boolean>(true);

  async function getUltrasonic() {
    const rawData = await fetch("/api/fetch-ultrasonic-data");
    const ultrasonicData = await rawData.json();
    return ultrasonicData.data;
  }

  useEffect(() => {
    getUltrasonic().then((res: any) => {
      setUltrasonicIrData(res);
    });
    setPageLoading(false);
  }, []);

  if (pageLoading) return <></>;
  return (
    <>
      <Head>
        <title>Ultrasonic Sensor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShellDemo>
        <Container>
          <Grid columns={12} mt={30}>
            <Grid.Col md={4}></Grid.Col>
            <Grid.Col md={4}>
              <Center mx={"auto"}>
                <Text>Ultrasonic SENSOR</Text>
              </Center>
              {ulrasonicData && ulrasonicData.length ? (
                <>
                  <UlraSonicTableComponent data={ulrasonicData} />
                </>
              ) : (
                <></>
              )}
            </Grid.Col>
            <Grid.Col md={4}></Grid.Col>
          </Grid>
        </Container>
      </AppShellDemo>
    </>
  );
}
